### ISSUE TITLE
log_wmc = tf.log(wmc_tmp) or log_wmc = tf.log(wmc)?

### ISSUE THREAD

**Issue by changlinzhang** [UCLA-StarAI/Semantic-Loss#2]
Hi, thank you for your work!
I wonder in `semi_supervised/semantic.py` 137 line:
Is it `log_wmc = tf.log(wmc_tmp)` or `log_wmc = tf.log(wmc)`?
Thank you in advance!

**Comment by YitaoLiang** [comment]
Hi,
  It is log_wmc = tf.log(wmc_tmp).
  wmc_tmp stores the wmc for every example. And wmc is the mean of it. The reason we use wmc_tmp here is because we need to add it to the existing loss (cross-entropy) for every sample. wmc here is more like a note-keeping which we print out to help debug and visualize.

**Comment by changlinzhang** [comment]
Got it. Thank you for your kind reply!
